Repository K-UniLab/Improfessor-BE, pull requests merged in 2025-07, with the labels that each got.

#24 [Docs] #23 - swagger authorize 추가
  src/main/java/org/unilab/improfessorbe/global/config/SwaggerConfig.java
Labels: doc

#25 [Deploy] #22 - dockerfile 추가
  .gitignore
  Dockerfile
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: deploy

#26 [ Feature ] #8 - 문제 다운로드 기능 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/parse/input/service/ConceptExtractorService.java
  src/main/java/org/unilab/improfessorbe/domain/parse/output/PdfExportService.java
  src/main/java/org/unilab/improfessorbe/domain/parse/util/FileLogUtil.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/dto/CachedProblemDto.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/dto/ProblemDownloadResponse.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/dto/ProblemGenerationResponse.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/CaffeineProblemCacheService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemCacheService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/controller/ProblemController.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiApiClient.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiDto.java
  src/main/resources/application.yml
Labels: feature

#29 [Fix] #27 - security 접근 가능 url 추가
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/java/org/unilab/improfessorbe/global/config/SwaggerConfig.java
Labels: bug fix, doc

#35 [#34] feat : 문제 생성후 캐시 Caffein > Redis 사용으로 변경
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/CaffeineProblemCacheService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/RedisProblemCacheService.java
  src/main/java/org/unilab/improfessorbe/global/exception/ErrorCode.java
Labels: bug fix

#33 [Fix] #32 - token 형식 수정
  src/main/java/org/unilab/improfessorbe/domain/user/service/CustomUserDetailsService.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/java/org/unilab/improfessorbe/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: doc, feature

#38 [Refactor] #37 - 현재 안쓰는 코드 주석 처리 및 삭제
  src/main/java/org/unilab/improfessorbe/domain/parse/input/service/ConceptExtractorService.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/validation/FileValidator.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/controller/ProblemController.java
  src/main/resources/application.yml
Labels: refactor

#40 [Feature] #39 - 유저 추천인 기능 추가
  src/main/java/org/unilab/improfessorbe/domain/parse/input/service/ConceptExtractorOurService.java
  src/main/java/org/unilab/improfessorbe/domain/user/domain/User.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserRecommendationService.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
  src/main/java/org/unilab/improfessorbe/global/exception/ErrorCode.java
Labels: bug fix, feature

#42 [Feature] #41 - 프론트 도메인 추가
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: bug fix, refactor

#44 [Featture] #43 - health check 설정 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature, deploy

#46 [Fix] #45 - gemini 응답 파싱 오류 수정
  src/main/java/org/unilab/improfessorbe/domain/parse/input/service/ConceptExtractorOurService.java
  src/main/java/org/unilab/improfessorbe/domain/parse/output/ProblemTextParser.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiApiClient.java
Labels: bug fix

#48 [Feature] #47 - resources/static/index.html 추가
  src/main/resources/static/index.html
Labels: doc

#50 [FIX] #49- 프론트 도메인 변경에 따른 cors 설정 변경
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
Labels: feature

#53 [#53] fix: user 정보 get method에서 비밀번호 필드 삭제
  src/main/java/org/unilab/improfessorbe/domain/user/controller/UserController.java
  src/main/java/org/unilab/improfessorbe/domain/user/domain/User.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/response/UserResponse.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
Labels: bug fix
