Repository K-UniLab/Improfessor-BE, pull requests merged in 2025-06, with the labels that each got.

#2 [Feature] #1 - 기본 Entity 생성
  src/main/java/org/unilab/improfessorbe/ImprofessorBeApplication.java
  src/main/java/org/unilab/improfessorbe/config/domain/BaseEntity.java
  src/main/java/org/unilab/improfessorbe/notice/controller/.gitkeep
  src/main/java/org/unilab/improfessorbe/notice/domain/Notice.java
  src/main/java/org/unilab/improfessorbe/notice/repository/NoticeRepository.java
  src/main/java/org/unilab/improfessorbe/notice/service/.gitkeep
  src/main/java/org/unilab/improfessorbe/user/controller/.gitkeep
  src/main/java/org/unilab/improfessorbe/user/domain/User.java
  src/main/java/org/unilab/improfessorbe/user/repository/UserRepository.java
  src/main/java/org/unilab/improfessorbe/user/service/.gitkeep
Labels: feature, setting

#4 [Feature] #3 - Global Setting
  src/main/java/org/unilab/improfessorbe/ImprofessorBeApplication.java
  src/main/java/org/unilab/improfessorbe/domain/notice/controller/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/notice/domain/Notice.java
  src/main/java/org/unilab/improfessorbe/domain/notice/repository/NoticeRepository.java
  src/main/java/org/unilab/improfessorbe/domain/notice/service/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/user/controller/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/user/domain/User.java
  src/main/java/org/unilab/improfessorbe/domain/user/repository/UserRepository.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/.gitkeep
  src/main/java/org/unilab/improfessorbe/global/common/ApiResponse.java
  src/main/java/org/unilab/improfessorbe/global/common/BaseEntity.java
  src/main/java/org/unilab/improfessorbe/global/config/JpaConfig.java
  src/main/java/org/unilab/improfessorbe/global/exception/CustomException.java
  src/main/java/org/unilab/improfessorbe/global/exception/ErrorCode.java
  src/main/java/org/unilab/improfessorbe/global/exception/GlobalExceptionHandler.java
Labels: feature, setting

#7 [Feature] #6 - Swagger 문서 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/global/config/SwaggerConfig.java
Labels: doc, feature

#11 [Feature] #5 - User 이메일 인증, 로그인, 회원가입 등 기본 로직 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/user/controller/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/user/controller/UserController.java
  src/main/java/org/unilab/improfessorbe/domain/user/domain/User.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/EmailVerificationResponse.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/response/EmailVerificationRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/response/UserResponse.java
  src/main/java/org/unilab/improfessorbe/domain/user/repository/UserRepository.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/user/service/EmailService.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
  src/main/java/org/unilab/improfessorbe/global/common/ApiResponse.java
  src/main/java/org/unilab/improfessorbe/global/common/BaseEntity.java
  src/main/java/org/unilab/improfessorbe/global/config/EmailConfig.java
  src/main/java/org/unilab/improfessorbe/global/config/RedisConfig.java
  src/main/java/org/unilab/improfessorbe/global/util/RedisUtil.java
  src/main/resources/application.yml
Labels: feature

#14 [Feature] #8 - gemini api 연동
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/FileValidationService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/controller/ProblemController.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/.gitkeep
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiApiClient.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiDto.java
  src/main/java/org/unilab/improfessorbe/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: feature

#17 [Fix] #16 - 회원가입 이메일 전송 로직 오류 수정
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
  src/main/java/org/unilab/improfessorbe/global/config/EmailConfig.java
  src/main/java/org/unilab/improfessorbe/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: bug fix

#21 [Feature] #18 - Spring Security Login 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/user/controller/UserController.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserLoginRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/org/unilab/improfessorbe/domain/user/dto/response/UserLoginResponse.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/CustomUserDetailsService.java
  src/main/java/org/unilab/improfessorbe/domain/user/service/UserService.java
  src/main/java/org/unilab/improfessorbe/global/config/SecurityConfig.java
  src/main/java/org/unilab/improfessorbe/global/exception/ErrorCode.java
  src/main/java/org/unilab/improfessorbe/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/unilab/improfessorbe/global/security/jwt/JwtExceptionFilter.java
  src/main/java/org/unilab/improfessorbe/global/security/jwt/JwtToken.java
  src/main/java/org/unilab/improfessorbe/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: feature

#20 [Feature] #19 중요한 개념(키워드, 문장) 추출 기능 추가
  build.gradle
  src/main/java/org/unilab/improfessorbe/domain/parse/dto/ConceptExtractionResult.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/convert/PdfFileParser.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/convert/PptFileParser.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/convert/PptxFileParser.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/convert/TextPreprocessor.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/service/ConceptExtractorService.java
  src/main/java/org/unilab/improfessorbe/domain/parse/input/validation/FileValidator.java
  src/main/java/org/unilab/improfessorbe/domain/parse/output/ProblemTextParser.java
  src/main/java/org/unilab/improfessorbe/domain/parse/util/FileLogUtil.java
  src/main/java/org/unilab/improfessorbe/domain/problem/application/service/ProblemService.java
  src/main/java/org/unilab/improfessorbe/domain/problem/controller/ProblemController.java
  src/main/java/org/unilab/improfessorbe/domain/problem/infrastructure/external/gemini/GeminiApiClient.java
  src/main/java/org/unilab/improfessorbe/global/exception/ErrorCode.java
Labels: refactor, feature
